<script lang="ts">
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import type { PageData } from './$types';
  export let data: PageData;
  const modeLabel = (mode: string) => mode === '100755' ? 'Executable' : mode === '120000' ? 'Symbolic link' : 'File';
</script>
<svelte:head><title>{data.manifest.pkgbase} · original recipe · omapkg</title></svelte:head>
<MaintainerShell active="imports" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><a href="/maintain/imports">Catalog imports</a><h1>{data.manifest.pkgbase}</h1><p>Original recipe files · {data.manifest.origin} · {data.summary.files} files</p></div><span class="tag">{data.summary.admissionRequired ? 'OPR admission required' : 'Source review required'}</span></header>
    <section class="workbench-panel"><h2>Preserved source</h2><p>File contents and modes match the retained Git commit proof. Capture does not approve a recipe or publish a package.</p><dl class="detail-list"><div class="detail-list__row"><dt>Repository</dt><dd><a href={data.manifest.repository} rel="noreferrer">{data.manifest.repository}</a></dd></div><div class="detail-list__row"><dt>Commit</dt><dd class="hash">{data.manifest.commit}</dd></div><div class="detail-list__row"><dt>Original directory</dt><dd>{data.manifest.directory || 'Repository root'}</dd></div><div class="detail-list__row"><dt>Recipe capture checksum</dt><dd class="hash">{data.record.sha256}</dd></div><div class="detail-list__row"><dt>Version from .SRCINFO</dt><dd>{data.summary.metadata?.version ?? 'Inspection required'}</dd></div></dl><p><a href={`/maintain/catalog?${new URLSearchParams({ q: data.manifest.pkgbase })}`}>Open ownership and source policy</a></p></section>
    <section class="workbench-panel"><h2>Review work</h2><ul>{#each data.summary.reviewNotes as note}<li>{note}</li>{/each}</ul>{#if data.summary.rebuildOn.length}<p>Imported rebuild triggers: <strong>{data.summary.rebuildOn.join(', ')}</strong></p>{/if}{#if data.summary.omarchy}<details><summary>Original Omarchy policy fields</summary><pre class="code-block">{JSON.stringify(data.summary.omarchy, null, 2)}</pre></details>{/if}{#if data.summary.metadata}<details><summary>Parsed .SRCINFO fields</summary><pre class="code-block">{JSON.stringify(data.summary.metadata, null, 2)}</pre></details>{/if}</section>
    <section class="workbench-panel"><h2>Captured package mapping</h2>{#each data.links as link}<div class="capture-mapping"><p><a href={`/maintain/imports/${link.import_id}?${new URLSearchParams({ q: data.manifest.pkgbase })}`}>{link.kind} · {link.channel} · {link.source_id}</a></p><p><strong>{link.comparison.matches ? 'Package metadata matches' : link.comparison.metadataPresent ? 'Package metadata differs' : 'Recipe inspection required'}</strong> · {link.comparison.capturedOutputs.join(', ')}</p><p>{link.reason}</p>{#if link.comparison.differences.length}<details><summary>{link.comparison.differences.length} mapping differences</summary><ul>{#each link.comparison.differences as difference}<li>{difference}</li>{/each}</ul></details>{/if}</div>{/each}</section>
    <section class="workbench-panel"><h2>Recipe files</h2><form method="GET" class="filter-bar"><div class="field"><label for="recipe-file">Retained file</label><select id="recipe-file" name="file" value={data.selected.path}>{#each data.manifest.files as file}<option value={file.path}>{file.path} · {modeLabel(file.mode)} · {file.object.size} bytes</option>{/each}</select></div><button class="button" type="submit">Inspect file</button></form><p>{modeLabel(data.selected.mode)} · {data.selected.object.size} bytes · <a href={`/maintain/recipes/${data.record.sha256}/file?${new URLSearchParams({ path: data.selected.path })}`}>Download original bytes</a></p><p class="hash">{data.selected.object.sha256}</p>{#if data.preview !== null}<pre class="code-block">{data.preview || '(Empty file)'}</pre>{:else}<p>Binary content or file exceeds the 256 KiB preview limit. Download retains all original bytes.</p>{/if}</section>
  </section>
</MaintainerShell>
<style>.capture-mapping + .capture-mapping { border-top: 1px solid var(--border); margin-top: var(--space-lg); padding-top: var(--space-md); } select { max-width: 100%; }</style>
