<script lang="ts">
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import { enhance } from '$app/forms';
  import { invalidateAll } from '$app/navigation';
  import { onMount } from 'svelte';
  import { startVisibleRefresh } from '$lib/visible-refresh';
  import type { ActionData, PageData } from './$types';
  export let data: PageData;
  export let form: ActionData;
  let busy = false;
  const pending = () => { busy = true; return async ({ update }: { update: () => Promise<void> }) => { await update(); busy = false; }; };
  onMount(() => startVisibleRefresh(() => data.inspections.some((inspection) => inspection.status === 'queued' || inspection.status === 'leased'), () => { void invalidateAll(); }));
  $: hasInspection = data.inspections.some((inspection) => inspection.current && inspection.metadata);
  const modeLabel = (mode: string) => mode === '100755' ? 'Executable' : mode === '120000' ? 'Symbolic link' : 'File';
</script>
<svelte:head><title>{data.manifest.pkgbase} · original recipe · omapkg</title></svelte:head>
<MaintainerShell active="imports" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><a href="/maintain/imports">Catalog imports</a><h1>{data.manifest.pkgbase}</h1><p>Original recipe files · {data.manifest.origin} · {data.summary.files} files</p></div><span class="tag">{data.summary.admissionRequired ? 'OPR admission required' : 'Source review required'}</span></header>
    {#if form?.error}<p class="form-notice form-notice--danger" role="alert">{form.error}</p>{:else if form?.success}<p class="notice-bar" role="status">Inspection request recorded. Results remain source evidence for review.</p>{/if}
    <section class="workbench-panel"><h2>Preserved source</h2><p>File contents and modes match the retained Git commit proof. Capture does not approve a recipe or publish a package.</p><dl class="detail-list"><div class="detail-list__row"><dt>Repository</dt><dd><a href={data.manifest.repository} rel="noreferrer">{data.manifest.repository}</a></dd></div><div class="detail-list__row"><dt>Commit</dt><dd class="hash">{data.manifest.commit}</dd></div><div class="detail-list__row"><dt>Original directory</dt><dd>{data.manifest.directory || 'Repository root'}</dd></div><div class="detail-list__row"><dt>Recipe capture checksum</dt><dd class="hash">{data.record.sha256}</dd></div><div class="detail-list__row"><dt>Version from original .SRCINFO</dt><dd>{data.summary.metadata?.version ?? 'Inspection required'}</dd></div></dl><p><a href={`/maintain/catalog?${new URLSearchParams({ q: data.manifest.pkgbase })}`}>Open ownership and source policy</a></p></section>
    <section class="workbench-panel"><h2>Review work</h2><ul>{#each data.summary.reviewNotes.filter((note) => !hasInspection || note !== data.summary.metadataError) as note}<li>{note}</li>{/each}{#if hasInspection && data.summary.metadataError}<li>Upstream .SRCINFO was unavailable or invalid. Signed sandbox metadata is retained below.</li>{/if}</ul>{#if data.summary.rebuildOn.length}<p>Imported rebuild triggers: <strong>{data.summary.rebuildOn.join(', ')}</strong></p>{/if}{#if data.summary.omarchy}<details><summary>Original Omarchy policy fields</summary><pre class="code-block">{JSON.stringify(data.summary.omarchy, null, 2)}</pre></details>{/if}{#if data.summary.metadata}<details><summary>Parsed .SRCINFO fields</summary><pre class="code-block">{JSON.stringify(data.summary.metadata, null, 2)}</pre></details>{/if}</section>
    <section class="workbench-panel"><h2>Sandbox metadata inspection</h2><p>Evaluate the retained PKGBUILD in a read-only container with networking disabled. A native worker signs the metadata result; package build and release gates remain required.</p>
      {#if data.canInspect && data.images.length}<form method="POST" action="?/inspect" class="review-form" use:enhance={pending}><div class="field"><label for="inspection-image">Pinned inspection image and target</label><select id="inspection-image" name="imageId" required>{#each data.images as image}<option value={image.id}>{image.label} · {image.architecture}</option>{/each}</select></div><div class="field"><label for="inspection-reason">Inspection reason</label><textarea id="inspection-reason" name="reason" required maxlength="2000" placeholder="Metadata to verify against this exact captured recipe"></textarea></div><button class="button" type="submit" disabled={busy}>{busy ? 'Queueing inspection…' : 'Request sandbox inspection'}</button></form>{:else if data.canInspect}<p>No enabled inspection image is available. <a href="/maintain/images">Configure a pinned build image</a>.</p>{/if}
      {#if data.summary.admissionRequired}<p class="notice-bar">AUR/ALARM source admission must bind this captured commit before inspection can run.</p>{/if}
      {#each data.inspections as inspection}<div class="capture-mapping"><p><strong>{inspection.architecture} · {inspection.status}</strong> · attempt {inspection.attempt}</p>{#if inspection.error}<p class="form-notice form-notice--danger">{inspection.error}</p>{/if}{#if inspection.status === 'leased' && inspection.lease_expires_at && inspection.lease_expires_at * 1000 < Date.now()}<p>Lease expired. Request inspection again to retry.</p>{/if}{#if inspection.metadata}<p>Inspected version: <strong>{inspection.metadata.version}</strong> · {inspection.metadata.outputs.length} outputs.</p>{#if !inspection.current}<p class="notice-bar">Inspection authority has changed. Check source admission, image and worker status before using this result.</p>{/if}<details><summary>Signed inspection metadata</summary><pre class="code-block">{JSON.stringify(inspection.metadata, null, 2)}</pre><p class="hash">{inspection.report_sha256}</p></details>{/if}{#if inspection.report_sha256}<p><a href={`/maintain/recipes/${data.record.sha256}/inspection?${new URLSearchParams({ job: inspection.id, attempt: String(inspection.attempt) })}`}>Download signed inspection evidence</a></p>{/if}{#if inspection.attempt > 1}<details><summary>Attempt history</summary><ul>{#each data.attempts.filter((attempt) => attempt.job_id === inspection.id) as attempt}<li><a href={`/maintain/recipes/${data.record.sha256}/inspection?${new URLSearchParams({ job: inspection.id, attempt: String(attempt.attempt) })}`}>Attempt {attempt.attempt}</a> · {attempt.error ?? 'Inspection passed'}</li>{/each}</ul></details>{/if}{#if data.canInspect && (inspection.status === 'queued' || inspection.status === 'leased')}<form method="POST" action="?/cancel" class="review-form" use:enhance={pending}><input type="hidden" name="jobId" value={inspection.id} /><div class="field"><label for={`cancel-${inspection.id}`}>Cancellation reason</label><input id={`cancel-${inspection.id}`} name="reason" required maxlength="2000" /></div><button class="button" type="submit" disabled={busy}>Cancel inspection</button></form>{/if}</div>{/each}
    </section>
    <section class="workbench-panel"><h2>Captured package mapping</h2>{#each data.links as link}<div class="capture-mapping"><p><a href={`/maintain/imports/${link.import_id}?${new URLSearchParams({ q: data.manifest.pkgbase })}`}>{link.kind} · {link.channel} · {link.source_id}</a></p><p><strong>{link.comparison.matches ? 'Package metadata matches' : link.comparison.metadataPresent ? 'Package metadata differs' : 'Recipe inspection required'}</strong> · {link.comparison.capturedOutputs.join(', ')}</p><p>{link.reason}</p>{#if link.inspected}<p>Compared using signed native {link.target} inspection.</p>{/if}{#if link.comparison.differences.length}<details><summary>{link.comparison.differences.length} mapping differences</summary><ul>{#each link.comparison.differences as difference}<li>{difference}</li>{/each}</ul></details>{/if}</div>{/each}</section>
    <section class="workbench-panel"><h2>Recipe files</h2><form method="GET" class="filter-bar"><div class="field"><label for="recipe-file">Retained file</label><select id="recipe-file" name="file" value={data.selected.path}>{#each data.manifest.files as file}<option value={file.path}>{file.path} · {modeLabel(file.mode)} · {file.object.size} bytes</option>{/each}</select></div><button class="button" type="submit">Inspect file</button></form><p>{modeLabel(data.selected.mode)} · {data.selected.object.size} bytes · <a href={`/maintain/recipes/${data.record.sha256}/file?${new URLSearchParams({ path: data.selected.path })}`}>Download original bytes</a></p><p class="hash">{data.selected.object.sha256}</p>{#if data.preview !== null}<pre class="code-block">{data.preview || '(Empty file)'}</pre>{:else}<p>Binary content or file exceeds the 256 KiB preview limit. Download retains all original bytes.</p>{/if}</section>
  </section>
</MaintainerShell>
<style>.capture-mapping + .capture-mapping { border-top: 1px solid var(--border); margin-top: var(--space-lg); padding-top: var(--space-md); } select { max-width: 100%; }</style>
