<script lang="ts">
  import { onMount } from 'svelte';
  import { enhance } from '$app/forms';
  import { invalidateAll } from '$app/navigation';
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import ImportCaptureUpload from '$lib/components/ImportCaptureUpload.svelte';
  import { startVisibleRefresh } from '$lib/visible-refresh';
  import type { ImportSource } from '$lib/imports';
  import type { ActionData, PageData } from './$types';
  export let data: PageData;
  export let form: ActionData;
  let kind = 'arch'; let channel = 'upstream'; let oprLayout = 'omapkg'; let busy = false;
  $: channels = kind === 'arch' ? ['upstream'] : kind === 'opr' && oprLayout === 'omapkg' ? ['stable', 'dev'] : ['stable', 'rc', 'edge'];
  $: if (!channels.includes(channel)) channel = channels[0];
  const sources = (json: string) => JSON.parse(json) as ImportSource[];
  const captureName = (kind: string) => ({ arch: 'Arch upstream', omarchy: 'Omarchy baseline', opr: 'Existing OPR' }[kind] ?? kind);
  onMount(() => startVisibleRefresh(() => data.jobs.some((job) => ['queued', 'capturing', 'uploading'].includes(job.status)), () => { void invalidateAll(); }));
</script>
<svelte:head><title>Repository imports · omapkg</title></svelte:head>
<MaintainerShell active="imports" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><h1>Repository imports</h1><p>Capture Arch upstream or existing OPR packages, then compare them with a captured Omarchy stable, RC or edge baseline.</p></div><a class="button" href="/maintain/catalog">Owned catalog</a></header>
    <p class="notice-bar">Capture → ownership review → OPR replacements → native builds → baseline reconciliation. Captured metadata is not a completed migration or an approved release.</p>
    {#if form?.error}<p class="form-notice form-notice--danger" role="alert">{form.error}</p>{/if}
    {#if data.canManage}<section class="workbench-panel"><h2>Start an import capture</h2><form method="POST" action="?/capture" class="form-grid" use:enhance={() => { busy = true; return async ({ update }) => { await update(); busy = false; }; }}><div class="field"><label for="capture-kind">What to import</label><select id="capture-kind" name="kind" bind:value={kind}><option value="arch">Arch upstream core / extra / multilib</option><option value="omarchy">Omarchy system baseline</option><option value="opr">Existing OPR packages</option></select></div><div class="field"><label for="capture-channel">Channel to capture</label><select id="capture-channel" name="channel" bind:value={channel}>{#each channels as item}<option value={item}>{item}</option>{/each}</select></div>{#if kind === 'opr'}<div class="field"><label for="opr-layout">Existing OPR repository</label><select id="opr-layout" name="oprLayout" bind:value={oprLayout}><option value="omapkg">This omapkg deployment</option><option value="omarchy">Omarchy package repository</option></select></div>{:else}<input type="hidden" name="oprLayout" value={oprLayout} />{/if}<div class="field field--full"><p>Both primary targets are captured: <strong>x86_64 and aarch64</strong>. Unavailable sources remain visible. An absent Omarchy ARM repository is a new target to qualify, not a blocker. ARM upstream reference metadata never authorizes ALARM package installation.</p><p class="field__hint">The pipeline fetches repository databases, retains their bytes/digests, and uploads package records. It does not execute recipes or install packages.</p></div><button class="button button--primary" type="submit" disabled={busy || !data.pipelineAvailable}>{busy ? 'Queueing capture…' : 'Start capture'}</button>{#if !data.pipelineAvailable}<p>The capture pipeline is unavailable. Configure it or upload an existing capture below.</p>{/if}</form></section>{/if}
    <section class="workbench-panel"><h2>Capture jobs</h2>{#if data.jobs.length}{#each data.jobs as job}{@const payload = JSON.parse(job.payload_json)}{@const progress = sources(job.progress_json)}<article class="import-job"><h3>{captureName(payload.kind)} · {payload.channel}</h3><p><strong>{job.status === 'captured' ? 'Metadata captured' : job.status}</strong> · {progress.length} source results recorded</p>{#if progress.length}<ul>{#each progress as source}<li>{source.collection} / {source.target}: {source.status === 'captured' ? `${source.entries} packages captured` : source.error || 'Unavailable'}</li>{/each}</ul>{/if}{#if job.error}<p class="form-notice form-notice--danger">{job.error}</p>{/if}{#if job.import_id}<a class="button" href={`/maintain/imports/${job.import_id}`}>Review capture and compare baseline</a>{/if}<p class="timestamp">Updated {new Date(job.updated_at * 1000).toISOString().replace('T', ' ').slice(0, 19)} UTC</p></article>{/each}{:else}<EmptyState title="No import captures started." description="Start with an Omarchy stable baseline and an Arch upstream capture. Existing OPR packages have their own import flow." />{/if}</section>
    <section class="workbench-panel"><h2>Captured inventories</h2>{#if data.imports.length}<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Inventory</th><th>Recorded packages</th><th>Unavailable sources</th><th>Next step</th></tr></thead><tbody>{#each data.imports as item}<tr><td><a href={`/maintain/imports/${item.id}`}>{captureName(item.manifest.kind)} · {item.manifest.channel}</a><div class="timestamp">{item.status === 'capturing' ? 'Upload in progress' : 'Metadata captured'}</div></td><td>{item.received} / {item.expected_count}</td><td>{item.manifest.sources.filter((source) => source.status === 'unavailable').length} unavailable sources</td><td>Review ownership, replacements and baseline comparison</td></tr>{/each}</tbody></table></div>{:else}<p>No sealed inventory yet. Progress remains visible above while sources are being captured.</p>{/if}</section>
    {#if data.canManage}<details class="workbench-panel"><summary>Upload a capture made outside the pipeline</summary><p>Use <code>opr-worker capture-catalog --source arch --arch all --output ./arch-capture</code>. Capture Omarchy with <code>--source omarchy --channel stable</code>; capture existing OPR with <code>--source opr --channel stable --opr-origin https://your-omapkg-host</code>.</p><ImportCaptureUpload /></details>{/if}
  </section>
</MaintainerShell>
<style>.import-job { padding-block: var(--space-lg); border-bottom: 1px solid var(--color-rule); }.import-job:last-child { border-bottom: 0; }</style>
