import type { Actor, Approval, Architecture, PackageRequest, Revision } from '../model';
import type { Env } from './env';
import { githubFetch } from './github';
import { audit, id, now, query } from './db';
import { parseRequest, PolicyError, requireMaintainer, requireSecurity, validateRevision } from './policy';
import { revisionRecipePolicy } from '../../../services/pipeline/recipe-policy';
import { reviewedRuntimeExceptions } from './runtime-evidence';
import { externalPackageSource } from '../distribution';
import { assertPreservedImportCurrent } from './preserved-imports';
import { assertAttestation, joinedBuild } from './release-evidence';
import { assertOutputEvidence, assertStandaloneReproducibilityContract, requireReproducibilityContract, type ReproducibilityContract } from './output-evidence';
import { buildArtifacts } from './build-outputs';
import { verifyR2Object } from './release-storage';
import { canonicalJson } from '../canonical-json';

export function pendingRequestStatements(db: D1Database, actor: Actor, value: ReturnType<typeof parseRequest>, requestId: string, timestamp: number): D1PreparedStatement[] {
  const rateKey = `request:${actor.id}`;

  return [
    db.prepare(`INSERT INTO rateLimit(id,key,count,lastRequest) VALUES(?,?,1,?)
      ON CONFLICT(key) DO UPDATE SET
        count=CASE WHEN rateLimit.lastRequest<=? THEN 1 WHEN rateLimit.count<10 THEN rateLimit.count+1 ELSE 11 END,
        lastRequest=CASE WHEN rateLimit.lastRequest<=? OR rateLimit.count<10 THEN ? ELSE rateLimit.lastRequest END`)
      .bind(id(), rateKey, timestamp, timestamp - 3_600, timestamp - 3_600, timestamp),
    db.prepare(`INSERT INTO requests(id,name,description,upstream_url,source_kind,area,declared_license,requested_by,status,created_at,updated_at)
      SELECT ?,?,?,?,?,?,?,?,'pending',?,? FROM rateLimit WHERE key=? AND count BETWEEN 1 AND 10`)
      .bind(requestId, value.name, value.description, value.upstream_url, value.source_kind, value.area, value.declared_license, actor.id, timestamp, timestamp, rateKey),
    db.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at) SELECT ?,?,?,?,? WHERE changes()=1`)
      .bind(actor.id, 'request.created', requestId, JSON.stringify(value), timestamp),
  ];
}

export async function submitRequest(env: Env, actor: Actor | null, input: unknown) {
  if (!actor) throw new PolicyError(401, 'Sign in with GitHub to request a package.');
  const value = parseRequest(input);

  const existing = await env.DB.prepare("SELECT id FROM requests WHERE name=? AND status NOT IN ('built','rejected','failed')")
    .bind(value.name).first<{ id: string }>();

  if (existing) throw new PolicyError(409, 'An active request for this package already exists.');
  const timestamp = now();
  const requestId = id();
  let result: D1Result[];

  try {
    result = await env.DB.batch(pendingRequestStatements(env.DB, actor, value, requestId, timestamp));
  } catch (cause) {
    if (cause instanceof Error && /UNIQUE constraint failed: requests\.name/i.test(cause.message)) {
      throw new PolicyError(409, 'An active request for this package already exists.');
    }

    throw cause;
  }

  if (!result[1]?.meta.changes) throw new PolicyError(429, 'Request limit reached. Try again in one hour.');

  return requestId;
}

export async function getRequest(env: Env, requestId: string) {
  const request = await env.DB.prepare('SELECT * FROM requests WHERE id=?').bind(requestId).first<PackageRequest>();

  if (!request) throw new PolicyError(404, 'Package request not found.');

  return request;
}

export async function startFactory(env: Env, actor: Actor | null, requestId: string, reason?: string) {
  const request = await getRequest(env, requestId) as PackageRequest & { factory_run_id?: string | null; preserved_import_id?: string | null };
  const reviewer = requireMaintainer(actor, request.area);

  if (request.preserved_import_id) throw new PolicyError(409, 'Original recipe imports cannot be regenerated by the factory. Review or replace the captured recipe.');

  if (externalPackageSource(request.upstream_url)) throw new PolicyError(409, 'This external packaging source needs a human-reviewed OPR replacement before generation.');

  if (reason !== undefined && (typeof reason !== 'string' || !reason.trim() || reason.length > 2_000)) {
    throw new PolicyError(400, 'Provide a regeneration reason, up to 2,000 characters.');
  }

  if (!['pending', 'failed', 'review', 'blocked'].includes(request.status)) throw new PolicyError(409, 'This request cannot start factory generation in its current state.');

  if (!env.PIPELINE) throw new PolicyError(503, 'Factory service is not configured.');
  const generationId = id();

  const result = await env.DB.batch([
    env.DB.prepare('UPDATE requests SET status=\'generating\',factory_run_id=?,updated_at=? WHERE id=? AND status=?').bind(generationId, now(), requestId, request.status),
    env.DB.prepare('INSERT INTO audit_events(actor,action,target,detail,created_at) SELECT ?,?,?,?,? WHERE changes()=1')
      .bind(reviewer.id, request.status === 'pending' ? 'request.approved' : 'factory.regenerated', requestId, JSON.stringify({ previousStatus: request.status, generationId, ...(reason === undefined ? {} : { reason: reason.trim() }) }), now()),
    ...(request.status === 'blocked' ? [env.DB.prepare("UPDATE dependency_blockers SET status='superseded',resolved_at=? WHERE request_id=? AND status='open' AND EXISTS (SELECT 1 FROM requests WHERE id=? AND status='generating' AND factory_run_id=?)").bind(now(), requestId, requestId, generationId)] : [])
  ]);

  if (!result[0].meta.changes) throw new PolicyError(409, 'Request changed. Refresh and retry.');

  try {
    const response = await env.PIPELINE.fetch('https://pipeline.internal/factory', {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId, generationId })
    });

    if (!response.ok) throw new Error(`Factory dispatch failed (${response.status}).`);
  } catch (cause) {
    const failure = await env.DB.batch([
      env.DB.prepare("UPDATE requests SET status='failed',updated_at=? WHERE id=? AND status='generating' AND factory_run_id=?").bind(now(), requestId, generationId),
      env.DB.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at)
        SELECT ?,?,?,?,? WHERE changes()=1`).bind('system', 'factory.dispatch_failed', requestId, '{}', now())
    ]);

    if (!failure[0]?.meta.changes) throw new PolicyError(409, 'Request changed. Refresh and retry.');
    throw new PolicyError(503, cause instanceof Error ? cause.message : 'Factory dispatch failed.');
  }
}

export async function rejectRequest(env: Env, actor: Actor | null, requestId: string, reason: string) {
  const request = await getRequest(env, requestId) as PackageRequest & { factory_run_id?: string | null; preserved_import_id?: string | null };
  const reviewer = requireMaintainer(actor, request.area);

  if (!reason.trim() || reason.length > 2000) throw new PolicyError(400, 'Provide a reason, up to 2,000 characters.');

  if (!['pending', 'review', 'failed', 'blocked'].includes(request.status) &&
    !(request.preserved_import_id && ['queued', 'building'].includes(request.status))) {
    throw new PolicyError(409, 'Only pending, failed, blocked or review requests and unpublished active imports can be rejected.');
  }

  const generationId = request.factory_run_id ?? null;

  const result = await env.DB.batch([
    env.DB.prepare(`UPDATE requests SET status='rejected', rejection_reason=?,updated_at=? WHERE id=? AND status=? AND factory_run_id IS ?
      ${request.preserved_import_id ? `AND NOT EXISTS(SELECT 1 FROM revisions r JOIN builds b ON b.revision_id=r.id JOIN releases published ON published.build_id=b.id WHERE r.request_id=requests.id)
        AND NOT EXISTS(SELECT 1 FROM revisions r JOIN cohort_recipe_ownership o ON o.recipe_revision_id=r.id JOIN cohorts c ON c.id=o.cohort_id
          WHERE r.request_id=requests.id AND c.phase IN ('publish','observe'))` : ''}`)
      .bind(reason.trim(), now(), requestId, request.status, generationId),
    env.DB.prepare('INSERT INTO audit_events(actor,action,target,detail,created_at) SELECT ?,?,?,?,? WHERE changes()=1')
      .bind(reviewer.id, 'request.rejected', requestId, JSON.stringify({ reason: reason.trim() }), now())
  ]);

  if (!result[0]?.meta.changes) throw new PolicyError(409, 'Request changed. Refresh and retry.');
}

async function privateArtifactPromotion(env: Env, revision: Revision): Promise<D1PreparedStatement[]> {
  const builds = await query<{ id: string; attempt: number; architecture: Architecture; status: string; factory_run_id: string; factory_attempt: number; input_lock_sha256: string | null; output_contract_json: string | null }>(env.DB,
    'SELECT id,attempt,architecture,status,factory_run_id,factory_attempt,input_lock_sha256,output_contract_json FROM builds WHERE revision_id=? AND private_candidate=1', revision.id);

  if (!builds.length) return [];
  const targets = [...new Set(JSON.parse(revision.architectures_json) as Architecture[])].sort();

  if (canonicalJson(builds.map((build) => build.architecture).sort()) !== canonicalJson(targets)) throw new PolicyError(409, 'Private factory outputs do not cover every required target.');
  const statements: D1PreparedStatement[] = [];

  for (const build of builds) {
    const run = await env.DB.prepare(`SELECT a.input_sha256 FROM factory_runs r JOIN factory_run_attempts a ON a.run_id=r.id AND a.attempt=r.successful_attempt
      WHERE r.id=? AND r.status='succeeded' AND a.attempt=? AND a.status='succeeded' AND a.candidate_revision_id=?
        AND EXISTS (SELECT 1 FROM json_each(a.build_ids_json) WHERE value=?)`)
      .bind(build.factory_run_id, build.factory_attempt, revision.id, build.id).first<{ input_sha256: string }>();

    if (!run || build.status !== 'succeeded') throw new PolicyError(409, 'Only the successful factory attempt can be reviewed for artifact reuse. Failed or unfinished candidates require intervention.');
    const stored = await joinedBuild(env, build.id);
    if (stored.smoke_passed !== 1) throw new PolicyError(409, 'Private factory runtime checks did not pass.');
    const worker = await env.DB.prepare('SELECT public_key FROM workers WHERE id=? AND status=\'active\'').bind(stored.worker_id).first<{ public_key: string }>();
    if (!worker) throw new PolicyError(409, 'Private build worker is no longer active.');
    await assertAttestation(stored, env);
    const provenance = JSON.parse(stored.provenance!) as Record<string, unknown>;
    if (provenance.factoryRunId !== build.factory_run_id || provenance.factoryAttempt !== build.factory_attempt || provenance.factoryInputSha256 !== run.input_sha256) throw new PolicyError(409, 'Private attestation is not bound to the successful factory attempt.');
    let reproducibility: ReproducibilityContract;
    let artifacts = await buildArtifacts(env.DB, build);

    if (stored.surface === 'recipe') {
      if (stored.artifact_key || stored.artifact_sha256 || stored.artifact_size !== null || stored.artifact_filename || artifacts.length) throw new PolicyError(409, 'Recipe-only factory candidates cannot retain distributable binaries.');
      reproducibility = await assertStandaloneReproducibilityContract(provenance.reproducibility, {
        architecture: build.architecture, recipeSha256: revision.recipe_sha256, imageDigest: String(provenance.imageDigest),
        sourceDateEpoch: revision.source_date_epoch, sources: JSON.parse(revision.sources_json), inputLockSha256: build.input_lock_sha256 ?? '',
        dependencyPlan: provenance.dependencyPlan ?? undefined,
      });
    } else if (provenance.schemaVersion === 2) {
      const report = await assertOutputEvidence(provenance, reviewedRuntimeExceptions(revision.sbom_json));
      reproducibility = await requireReproducibilityContract(report);
      if (report.attempt !== build.attempt || canonicalJson(report.outputContract) !== canonicalJson(JSON.parse(build.output_contract_json ?? 'null')) ||
          (report.frozenInputs?.lock.sha256 ?? null) !== build.input_lock_sha256) throw new PolicyError(409, 'Private build evidence differs from its retained execution inputs.');
    } else {
      if (build.output_contract_json || build.input_lock_sha256 || !stored.artifact_filename || !stored.artifact_sha256 || !stored.artifact_size || !stored.artifact_key) throw new PolicyError(409, 'Private standalone build is missing its retained artifact.');
      reproducibility = await assertStandaloneReproducibilityContract(provenance.reproducibility, {
        architecture: build.architecture, recipeSha256: revision.recipe_sha256, imageDigest: String(provenance.imageDigest),
        sourceDateEpoch: revision.source_date_epoch, sources: JSON.parse(revision.sources_json), inputLockSha256: '',
        dependencyPlan: provenance.dependencyPlan ?? undefined,
        output: { filename: stored.artifact_filename, sha256: stored.artifact_sha256, size: stored.artifact_size },
      });
      artifacts = [{ key: stored.artifact_key, filename: stored.artifact_filename, sha256: stored.artifact_sha256, size: stored.artifact_size }];
    }

    if (canonicalJson(reproducibility.execution) !== canonicalJson({ runId: build.factory_run_id, attempt: build.factory_attempt, inputSha256: run.input_sha256 })) throw new PolicyError(409, 'Private reproducibility evidence is not bound to the successful factory attempt.');
    if (stored.surface === 'binary' && canonicalJson(artifacts.map(({ filename, sha256, size }) => ({ filename, sha256, size })).sort((a, b) => a.filename.localeCompare(b.filename))) !==
        canonicalJson([...reproducibility.outputs.files].sort((a, b) => a.filename.localeCompare(b.filename)))) throw new PolicyError(409, 'Private artifact set differs from the signed reproducibility evidence.');
    for (const artifact of artifacts) await verifyR2Object(env, artifact.key, artifact.sha256, artifact.size);
    statements.push(env.DB.prepare(`UPDATE builds SET private_candidate=0 WHERE id=? AND private_candidate=1 AND status='succeeded' AND attempt=?
      AND provenance=? AND provenance_signature=? AND input_lock_sha256 IS ? AND output_contract_json IS ?
      AND EXISTS (SELECT 1 FROM workers w WHERE w.id=builds.worker_id AND w.public_key=? AND w.status='active')
      AND EXISTS (SELECT 1 FROM requests q JOIN revisions v ON v.request_id=q.id WHERE v.id=builds.revision_id AND q.status='queued'
        AND v.id=(SELECT latest.id FROM revisions latest WHERE latest.request_id=q.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
        AND (q.preserved_import_id IS NULL OR EXISTS(SELECT 1 FROM current_preserved_recipe_imports i WHERE i.id=q.preserved_import_id AND (i.revision_id=v.id OR i.revision_id=v.preserved_origin_revision_id))))
      AND EXISTS (SELECT 1 FROM factory_runs r JOIN factory_run_attempts a ON a.run_id=r.id AND a.attempt=r.successful_attempt
        WHERE r.id=builds.factory_run_id AND r.status='succeeded' AND a.status='succeeded' AND a.attempt=builds.factory_attempt AND a.candidate_revision_id=builds.revision_id)
      AND (input_lock_sha256 IS NULL OR EXISTS (SELECT 1 FROM current_input_locks l JOIN build_input_selections s ON s.lock_sha256=l.sha256
        WHERE l.sha256=builds.input_lock_sha256 AND s.recipe_revision_id=builds.revision_id AND s.architecture=builds.architecture AND s.cohort_id=l.cohort_id AND s.cohort_revision=l.cohort_revision))
      AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=builds.revision_id AND a.kind='area' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
      AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=builds.revision_id AND a.kind='security' AND a.manifest_sha256=? AND a.revoked_at IS NULL)`)
      .bind(build.id, build.attempt, stored.provenance, stored.provenance_signature, build.input_lock_sha256, build.output_contract_json, worker.public_key, revision.manifest_sha256, revision.manifest_sha256));
    statements.push(env.DB.prepare('INSERT INTO distribution_assertions(expected,actual) VALUES(1,changes())'));
  }
  return statements;
}

export async function approveRevision(env: Env, actor: Actor | null, requestId: string, revisionId: string, kind: string, reason?: string, customShellAcknowledged = false, runtimeExceptionsAcknowledged = false) {
  if (!['area', 'security'].includes(kind)) throw new PolicyError(400, 'Choose area or security approval.');

  if (reason !== undefined && (typeof reason !== 'string' || !reason.trim() || reason.length > 2_000)) throw new PolicyError(400, 'Provide a review reason, up to 2,000 characters.');
  const reviewReason = reason?.trim();
  const request = await getRequest(env, requestId) as PackageRequest & { factory_run_id?: string | null };
  const reviewer = kind === 'security' ? requireSecurity(actor) : requireMaintainer(actor, request.area);

  if (!['review', 'queued'].includes(request.status)) throw new PolicyError(409, 'This request is not awaiting review.');

  const revision = await env.DB.prepare('SELECT * FROM revisions WHERE request_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1')
    .bind(requestId).first<Revision>();

  if (!revision || revision.id !== revisionId) throw new PolicyError(409, 'Only the latest revision can be approved.');
  await validateRevision(revision);
  await assertPreservedImportCurrent(env.DB, revision);
  const generationId = request.factory_run_id ?? null;
  const timestamp = now();

  if (request.status === 'queued' && await env.DB.prepare(`SELECT 1 FROM builds WHERE revision_id=? AND private_candidate=0 AND status IN ('queued','leased','succeeded') LIMIT 1`).bind(revisionId).first()) {
    throw new PolicyError(409, 'This request is already queued for a worker.');
  }

  const recipePolicy = revisionRecipePolicy(revision.sbom_json);

  if (recipePolicy.mode === 'custom-shell' && customShellAcknowledged !== true) {
    throw new PolicyError(400, 'Acknowledge review of custom shell, including preparation, packaging, public recipe, and smoke commands.');
  }

  if (reviewedRuntimeExceptions(revision.sbom_json).length && runtimeExceptionsAcknowledged !== true) {
    throw new PolicyError(400, 'Acknowledge each exact runtime analysis exception and its reason.');
  }

  const result = await env.DB.batch([
    env.DB.prepare(`INSERT INTO approvals(id,revision_id,actor,kind,manifest_sha256,created_at)
      SELECT ?,?,?,?,?,? FROM requests q
      WHERE q.id=? AND (q.status='review' OR (q.status='queued' AND NOT EXISTS (
        SELECT 1 FROM builds b WHERE b.revision_id=? AND b.private_candidate=0 AND b.status IN ('queued','leased','succeeded')))) AND q.factory_run_id IS ?
        AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=q.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
      ON CONFLICT(revision_id,kind) DO UPDATE SET actor=excluded.actor,manifest_sha256=excluded.manifest_sha256,
        created_at=excluded.created_at,revoked_at=NULL,revoked_by=NULL`)
      .bind(id(), revisionId, reviewer.id, kind, revision.manifest_sha256, timestamp, requestId, revisionId, generationId, revisionId),
    env.DB.prepare('INSERT INTO audit_events(actor,action,target,detail,created_at) SELECT ?,?,?,?,? WHERE changes()=1')
      .bind(reviewer.id, 'revision.approved', requestId, JSON.stringify({ revisionId, kind, manifestSha256: revision.manifest_sha256, reason: reviewReason, customShellAcknowledged, runtimeExceptionsAcknowledged }), timestamp)
  ]);

  const state = await env.DB.prepare(`SELECT status,factory_run_id,
      (SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1) AS latest_revision_id
    FROM requests WHERE id=?`).bind(requestId).first<{ status: string; factory_run_id: string | null; latest_revision_id: string | null }>();

  if (!state || !['review', 'queued'].includes(state.status) || state.latest_revision_id !== revisionId || (state.factory_run_id ?? null) !== generationId) {
    throw new PolicyError(409, 'Request changed. Refresh and retry.');
  }

  if (state.status === 'queued' && await env.DB.prepare(`SELECT 1 FROM builds WHERE revision_id=? AND private_candidate=0 AND status IN ('queued','leased','succeeded') LIMIT 1`).bind(revisionId).first()) {
    throw new PolicyError(409, 'This request is already queued for a worker.');
  }

  // Repeating approval retries PR merge/queueing after a transient GitHub failure.
  const approvals = await query<Approval>(env.DB, 'SELECT * FROM approvals WHERE revision_id=? AND manifest_sha256=? AND revoked_at IS NULL', revisionId, revision.manifest_sha256);

  if (approvals.length === 2) {
    const privatePromotion = await privateArtifactPromotion(env, revision);
    // Lock review finalization before the external GitHub merge. No normal reject or regenerate action accepts queued state.
    const finalizingAt = now();

    const finalizing = state.status === 'review'
      ? await env.DB.batch([
        env.DB.prepare(`UPDATE requests SET status='queued',updated_at=? WHERE id=? AND status='review' AND factory_run_id IS ?
          AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='area' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='security' AND a.manifest_sha256=? AND a.revoked_at IS NULL)`)
          .bind(finalizingAt, requestId, generationId, revisionId, revisionId, revision.manifest_sha256, revisionId, revision.manifest_sha256),
        env.DB.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at)
          SELECT ?,?,?,?,? WHERE changes()=1`)
          .bind(reviewer.id, 'revision.finalizing', requestId, JSON.stringify({ revisionId, manifestSha256: revision.manifest_sha256 }), finalizingAt),
      ])
      : await env.DB.batch([
        env.DB.prepare(`UPDATE requests SET updated_at=? WHERE id=? AND status='queued' AND factory_run_id IS ?
          AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
          AND NOT EXISTS (SELECT 1 FROM builds b WHERE b.revision_id=? AND b.private_candidate=0 AND b.status IN ('queued','leased','succeeded'))
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='area' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='security' AND a.manifest_sha256=? AND a.revoked_at IS NULL)`)
          .bind(finalizingAt, requestId, generationId, revisionId, revisionId, revisionId, revision.manifest_sha256, revisionId, revision.manifest_sha256),
        env.DB.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at)
          SELECT ?,?,?,?,? WHERE changes()=1`)
          .bind(reviewer.id, 'revision.finalizing', requestId, JSON.stringify({ revisionId, manifestSha256: revision.manifest_sha256, resumed: true }), finalizingAt),
      ]);

    if (!finalizing[0]?.meta.changes) throw new PolicyError(409, 'Request changed. Refresh and retry.');

    // Queue only after the exact reviewed commit is merged into the source of truth.
    try {
      await mergeRecipePR(env, revision);
    } catch (cause) {
      await reopenFinalization(env, requestId, generationId, revisionId, 'recipe merge failed');
      throw cause;
    }

    const architectures = [...new Set(JSON.parse(revision.architectures_json) as Architecture[])];

    try {
      await env.DB.batch([
        ...privatePromotion,
        ...architectures.map((architecture) => env.DB.prepare(`INSERT INTO builds(id,revision_id,architecture,status,created_at)
          SELECT ?,?,?,'queued',? FROM requests q
          WHERE q.id=? AND q.status='queued' AND q.factory_run_id IS ?
            AND NOT EXISTS (SELECT 1 FROM builds b WHERE b.revision_id=? AND b.private_candidate=1)
            AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=q.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
            AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='area' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
            AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='security' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
          ON CONFLICT(revision_id,architecture) DO UPDATE SET
            status=CASE WHEN status IN ('cancelled','failed') THEN 'queued' ELSE status END,
            worker_id=CASE WHEN status IN ('cancelled','failed') THEN NULL ELSE worker_id END,
            lease_token=CASE WHEN status IN ('cancelled','failed') THEN NULL ELSE lease_token END,
            lease_expires_at=CASE WHEN status IN ('cancelled','failed') THEN NULL ELSE lease_expires_at END,
            error=CASE WHEN status IN ('cancelled','failed') THEN NULL ELSE error END,
            finished_at=CASE WHEN status IN ('cancelled','failed') THEN NULL ELSE finished_at END`)
          .bind(id(), revisionId, architecture, timestamp, requestId, generationId, revisionId, revisionId, revisionId, revision.manifest_sha256, revisionId, revision.manifest_sha256)),
        env.DB.prepare(`UPDATE requests SET updated_at=? WHERE id=? AND status='queued' AND factory_run_id IS ?
          AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='area' AND a.manifest_sha256=? AND a.revoked_at IS NULL)
          AND EXISTS (SELECT 1 FROM approvals a WHERE a.revision_id=? AND a.kind='security' AND a.manifest_sha256=? AND a.revoked_at IS NULL)`)
          .bind(now(), requestId, generationId, revisionId, revisionId, revision.manifest_sha256, revisionId, revision.manifest_sha256),
        env.DB.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at)
          SELECT ?,?,?,?,? WHERE changes()=1`)
          .bind(reviewer.id, 'builds.queued', requestId, JSON.stringify({ revisionId, architectures }), now()),
      ]);
    } catch (cause) {
      await reopenFinalization(env, requestId, generationId, revisionId, 'build queue failed');
      throw cause;
    }

    const settled = await env.DB.prepare(`SELECT status,
        EXISTS (SELECT 1 FROM builds b WHERE b.revision_id=? AND b.private_candidate=0 AND b.status IN ('queued','leased','succeeded')) AS has_jobs
      FROM requests WHERE id=? AND factory_run_id IS ?
        AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)`)
      .bind(revisionId, requestId, generationId, revisionId)
      .first<{ status: string; has_jobs: number }>();

    if (!settled || settled.status !== 'queued') throw new PolicyError(409, 'Request changed. Refresh and retry.');

    if (!settled.has_jobs) {
      await reopenFinalization(env, requestId, generationId, revisionId, 'approval changed during finalization');
      throw new PolicyError(409, 'Approval changed while the recipe was finalizing. Review and approve the current revision again.');
    }
  }
}

async function reopenFinalization(env: Env, requestId: string, generationId: string | null, revisionId: string, reason: string) {
  const timestamp = now();
  await env.DB.batch([
    env.DB.prepare(`UPDATE requests SET status='review',updated_at=? WHERE id=? AND status='queued' AND factory_run_id IS ?
      AND ?=(SELECT latest.id FROM revisions latest WHERE latest.request_id=requests.id ORDER BY latest.created_at DESC,latest.rowid DESC LIMIT 1)
      AND NOT EXISTS (SELECT 1 FROM builds b WHERE b.revision_id=? AND b.private_candidate=0 AND b.status IN ('queued','leased','succeeded'))`)
      .bind(timestamp, requestId, generationId, revisionId, revisionId),
    env.DB.prepare(`INSERT INTO audit_events(actor,action,target,detail,created_at)
      SELECT 'system','revision.finalization_reopened',?,?,? WHERE changes()=1`)
      .bind(requestId, JSON.stringify({ revisionId, reason }), timestamp),
  ]);
}

async function mergeRecipePR(env: Env, revision: Revision) {
  if (!env.GITHUB_REPOSITORY) throw new PolicyError(503, 'GitHub repository integration is not configured.');
  const prefix = `https://github.com/${env.GITHUB_REPOSITORY}/pull/`;

  if (!revision.pr_url?.startsWith(prefix)) throw new PolicyError(409, 'Recipe PR is outside the configured source-of-truth repository.');
  const number = revision.pr_url.slice(prefix.length);

  if (!/^\d+$/.test(number)) throw new PolicyError(409, 'Invalid recipe pull request.');
  const url = `https://api.github.com/repos/${env.GITHUB_REPOSITORY}/pulls/${number}`;
  const response = await githubFetch(env, url);

  if (!response.ok) throw new PolicyError(502, 'Could not verify the recipe pull request.');
  const pr = await response.json() as { head: { sha: string }; merged: boolean };

  if (pr.head.sha !== revision.commit_sha) throw new PolicyError(409, 'Recipe PR changed after generation. Generate and review a new revision.');

  if (pr.merged) return;
  const merged = await githubFetch(env, `${url}/merge`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sha: revision.commit_sha, merge_method: 'squash' }) });

  if (!merged.ok || !(await merged.json() as { merged?: boolean }).merged) throw new PolicyError(409, 'GitHub could not merge the reviewed recipe. Resolve PR checks, then retry.');
}
