<script lang="ts">
  import { enhance } from '$app/forms';
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import type { ActionData, PageData } from './$types';

  export let data: PageData;

  export let form: ActionData;

  let busy = false;

  $: canDecide = data.actor.role !== 'maintainer' || data.parents.every((parent) => data.actor.areas.includes(parent.area));

  const pending = () => { busy = true;

 return async ({ update }: { update: () => Promise<void> }) => { await update(); busy = false; }; };
</script>
<svelte:head><title>{data.manifest.name} · dependency proposal · omapkg</title></svelte:head>
<MaintainerShell active="dependencies" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><a href="/maintain/dependencies">Dependency proposals</a><h1>{data.manifest.relation}</h1><p>{data.manifest.architecture} · proposal revision {data.proposal.revision} · {data.proposal.status}</p></div>{#if data.proposal.dependency_request_id}<a class="button" href={`/maintain/requests/${data.proposal.dependency_request_id}`}>Open packaging request</a>{/if}</header>
    {#if form?.error}<p class="form-notice form-notice--danger" role="alert">{form.error}</p>{:else if form?.success}<p class="notice-bar" role="status">Decision recorded. Admission does not approve a build or release.</p>{/if}
    {#if data.proposal.decision_reason}<p class="notice-bar">Decision: {data.proposal.decision_reason}</p>{/if}
    <section class="workbench-panel"><h2>Why this package is needed</h2><p>No eligible provider satisfied this relation on the target architecture. Review shared parents and source scope. A rejected or unfinished proposal never enables external repository fallback.</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Parent package</th><th>Evidence</th><th>Required action</th></tr></thead><tbody>{#each data.parents as parent}<tr><td><a href={`/maintain/requests/${parent.request_id}`}>{parent.name}</a><div class="timestamp">{parent.area} · {parent.architecture}</div></td><td>{parent.detail}</td><td>{parent.status === 'open' ? 'Waiting for an eligible owned provider' : parent.status}</td></tr>{/each}</tbody></table></div></section>
    <section class="workbench-panel"><h2>Proposed OPR source</h2><dl class="detail-list"><div class="detail-list__row"><dt>Package identity</dt><dd>{data.manifest.name}{#if data.manifest.targetPkgbase} · variant of <a href={`/maintain/catalog/${data.manifest.targetPkgbase}`}>{data.manifest.targetPkgbase}</a>{/if}</dd></div><div class="detail-list__row"><dt>Authoritative upstream</dt><dd>{#if data.manifest.upstreamUrl}<a href={data.manifest.upstreamUrl}>{data.manifest.upstreamUrl}</a>{:else}Not selected. A maintainer must review a source before admission.{/if}</dd></div><div class="detail-list__row"><dt>Origin / license hint</dt><dd>{data.manifest.origin} / {data.manifest.license}</dd></div>{#if data.manifest.referenceUrl}<div class="detail-list__row"><dt>Reference evidence</dt><dd><a href={data.manifest.referenceUrl}>{data.manifest.referenceUrl}</a> · not an approved package source</dd></div>{/if}</dl><details><summary>Exact proposal digest</summary><p class="hash">{data.proposal.manifest_sha256}</p></details></section>
    {#if canDecide && ['proposed', 'declined'].includes(data.proposal.status)}
      <details class="workbench-panel" open={!data.manifest.upstreamUrl}><summary>{data.proposal.status === 'declined' ? 'Propose an alternative for review' : 'Review or amend the source proposal'}</summary>
        <form method="POST" action="?/revise" class="form-grid" use:enhance={pending}><input type="hidden" name="digest" value={data.proposal.manifest_sha256} /><div class="field"><label for="proposal-name">OPR package name</label><input id="proposal-name" name="name" value={data.manifest.name} required /></div><div class="field"><label for="proposal-target">Existing catalog build identity, if adding a variant</label><input id="proposal-target" name="targetPkgbase" value={data.manifest.targetPkgbase ?? ''} /><p class="field__hint">Use the existing identity for an ARM port; do not create a competing same-name package.</p></div><div class="field"><label for="proposal-source">Authoritative upstream URL</label><input id="proposal-source" name="upstreamUrl" type="url" value={data.manifest.upstreamUrl ?? ''} /></div><div class="field"><label for="proposal-kind">Source type</label><select id="proposal-kind" name="sourceKind" value={data.manifest.sourceKind ?? 'git'}><option value="git">Git</option><option value="archive">Archive</option></select></div><div class="field"><label for="proposal-origin">Reference origin</label><select id="proposal-origin" name="origin" value={data.manifest.origin}><option value="unknown">Still investigating</option><option value="upstream">Authoritative upstream</option><option value="aur-reference">AUR reference</option><option value="alarm-reference">ALARM reference</option></select></div><div class="field"><label for="proposal-reference">Reference URL</label><input id="proposal-reference" name="referenceUrl" type="url" value={data.manifest.referenceUrl ?? ''} /></div><div class="field"><label for="proposal-license">Declared license</label><input id="proposal-license" name="license" required value={data.manifest.license} /></div><div class="field field--full"><label for="proposal-reason">What changed and why</label><textarea id="proposal-reason" name="reason" rows="2" required maxlength="2000"></textarea></div><button class="button" type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save a reviewed source proposal'}</button></form>
      </details>
    {/if}
    {#if data.proposal.status === 'proposed' && canDecide}
      <section class="workbench-panel"><h2>Human admission decision</h2><p>Admitting creates or links a normal packaging request for all current parents. Source inspection, recipe review, native tests and release authority still apply. The current system version is not changed by this decision.</p>
        <form class="filter-bar" method="GET"><div class="field"><label for="request-match">Search existing package requests</label><input id="request-match" type="search" name="q" value={data.search} /></div><button class="button" type="submit">Find a request</button></form>
        <form class="review-form" method="POST" action="?/admit" use:enhance={pending}><input type="hidden" name="digest" value={data.proposal.manifest_sha256} /><div class="field"><label for="existing-request">Packaging request</label><select id="existing-request" name="existingRequestId"><option value="">Create a new pending request from the reviewed source</option>{#each data.matches as match}<option value={match.id}>{match.name} · {match.status} · {match.area}</option>{/each}</select><p class="field__hint">A linked request must eventually supply the exact required version and architecture; selecting it cannot clear the blocker by itself.</p></div><div class="field"><label for="admission-reason">Admission reason</label><textarea id="admission-reason" name="reason" required maxlength="2000" rows="2"></textarea></div><button class="button button--primary" type="submit" disabled={busy}>{busy ? 'Recording decision…' : 'Admit packaging work'}</button></form>
        <details><summary>Decline this source proposal</summary><form class="review-form" method="POST" action="?/decline" use:enhance={pending}><input type="hidden" name="digest" value={data.proposal.manifest_sha256} /><div class="field"><label for="decline-reason">Why this package cannot be admitted</label><textarea id="decline-reason" name="reason" required maxlength="2000" rows="2"></textarea></div><button class="button" type="submit" disabled={busy}>Decline and keep parents blocked</button></form></details>
      </section>
    {:else if !canDecide}<p class="notice-bar">This shared proposal affects areas outside your authority. An authorized owner or security maintainer must decide.</p>{/if}
    <section class="workbench-panel"><h2>Proposal history</h2>{#each data.history as revision}<p><a href={`/maintain/dependencies/${revision.id}`}>Revision {revision.revision}</a> · {revision.status}{#if revision.decision_reason} · {revision.decision_reason}{/if}</p>{/each}</section>
  </section>
</MaintainerShell>
