<script lang="ts">
  import { enhance } from '$app/forms';
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import type { PageData, ActionData } from './$types';
  export let data: PageData; export let form: ActionData;
  $: currentReviews = data.reviews.filter((review) => !review.revoked_at);
  $: canSecurity = data.role === 'security' || data.role === 'admin';
  const object = (digest: string, filename?: string) => `/api/maintain/inputs/objects/${digest}${filename ? `?filename=${encodeURIComponent(filename)}` : ""}`;
  const page = (offset: number) => `?search=${encodeURIComponent(data.search)}&offset=${offset}`;
</script>
<svelte:head><title>{data.recipe?.name} input lock · omapkg</title></svelte:head>
<MaintainerShell active="inputs" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><span class="eyebrow">{data.lock.purpose} inputs · {data.lock.architecture}</span><h1>{data.recipe?.name ?? 'Native build'} input lock</h1><p>{data.recipe?.title} · cohort revision {data.lock.cohort_revision}</p></div><a class="button" href={`/maintain/cohorts/${data.lock.cohort_id}`}>Open cohort</a></header>
    {#if form?.error}<p class="form-notice form-notice--danger" role="alert">{form.error}</p>{:else if form?.success}<p class="notice-bar" role="status">Input decision recorded.</p>{/if}
    <p class="notice-bar">{data.lock.purpose === 'bootstrap' ? 'External packages seed private native rebuilds. This lock cannot qualify a published release.' : 'Every package input references a retained signed native build. Final cohort checks and release approval remain required.'}</p>
    <section class="workbench-panel"><h2>Retained closure</h2><p>{data.lock.reason}</p><p><strong>{data.lock.status === 'preparing' ? 'Retention incomplete' : data.current ? 'Current independent reviews' : 'Awaiting reviews or current recipe authority'}</strong> · {data.selected ? 'Selected for this build target' : 'Not selected'}</p><div class="detail-list"><div class="detail-list__row"><span class="detail-list__key">Input lock</span><a class="detail-list__value hash" href={object(data.lock.sha256)}>{data.lock.sha256}</a></div><div class="detail-list__row"><span class="detail-list__key">Recipe</span><a class="detail-list__value hash" href={`/maintain/requests/${data.recipe?.request_id}`}>{data.manifest.recipeSha256}</a></div><div class="detail-list__row"><span class="detail-list__key">Helper image</span><span class="detail-list__value hash">{data.manifest.helperImage}</span></div><div class="detail-list__row"><span class="detail-list__key">Retained files</span><span class="detail-list__value">{data.lock.object_count} objects · {(data.lock.transfer_bytes / 1024 ** 2).toFixed(1)} MiB execution transfer</span></div><div class="detail-list__row"><span class="detail-list__key">Transfer limit</span><span class="detail-list__value">{(data.manifest.transferLimitBytes / 1024 ** 3).toFixed(2)} GiB</span></div><div class="detail-list__row"><span class="detail-list__key">Build clock</span><span class="detail-list__value">SOURCE_DATE_EPOCH {data.manifest.sourceDateEpoch} · UTC</span></div></div><p><a href={object(data.manifest.helperArchive.sha256)}>Download helper archive</a> · <a href={object(data.manifest.makepkgConfig.sha256)}>Review makepkg.conf</a></p><p>Object hashes are checked on retention. Native preparation independently checks signatures, package metadata, helper identity and the complete installed inventory.</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Environment</th><th>Packages</th><th>Package bytes</th><th>Inventory checksum</th></tr></thead><tbody>{#each data.manifest.environments as environment}<tr><td>{environment.name}</td><td>{environment.packageCount}</td><td>{(environment.totalBytes / 1024 ** 2).toFixed(1)} MiB</td><td class="hash">{environment.inventorySha256}</td></tr>{/each}</tbody></table></div></section>
    <section class="workbench-panel"><h2>Independent reviews</h2><p>System and security reviewers approve the exact closure, source records, signing fingerprints and helper image.</p>{#each data.reviews as review}<article class="input-review"><h3>{review.kind === 'area' ? 'System' : 'Security'} · {data.actorNames?.[review.actor] ?? review.actor}</h3><p>{review.reason}</p><p class="timestamp">{review.revoked_at ? `Revoked: ${review.revoke_reason}` : 'Active review'}</p>{#if !review.revoked_at && data.canManage && (review.actor === data.actorId || canSecurity)}<form method="POST" action="?/revoke" use:enhance><input type="hidden" name="reviewId" value={review.id} /><div class="field"><label for={`revoke-${review.id}`}>Reason to revoke</label><input id={`revoke-${review.id}`} name="reason" required maxlength="2000" /></div><button class="button button--danger" type="submit">Revoke input review</button></form>{/if}</article>{/each}{#if data.canManage && !currentReviews.some((review) => review.actor === data.actorId)}<form method="POST" action="?/review" class="review-form" use:enhance><div class="field"><label for="review-kind">Review responsibility</label><select id="review-kind" name="kind" required>{#if !currentReviews.some((review) => review.kind === 'area')}<option value="area">System inputs</option>{/if}{#if canSecurity && !currentReviews.some((review) => review.kind === 'security')}<option value="security">Security and signing keys</option>{/if}</select></div><div class="field"><label for="review-reason">Review evidence</label><textarea id="review-reason" name="reason" required maxlength="2000" placeholder="How sources, fingerprints and the retained helper were checked"></textarea></div><button class="button button--primary" type="submit">Approve exact input lock</button></form>{/if}{#if data.canManage && data.current && !data.selected}<form method="POST" action="?/select" class="review-form" use:enhance><div class="field"><label for="select-reason">Use these inputs</label><input id="select-reason" name="reason" required maxlength="2000" placeholder="Private native rebuild using this reviewed closure" /></div><button class="button button--primary" type="submit">Select and queue native build</button></form>{/if}</section>
    <section class="workbench-panel"><h2>Owned input coverage</h2><p><strong>{data.ownedAvailable} of {data.ownedRequired}</strong> exact package versions have signed native replacements. Assembly preserves versions and requires a new independent review.</p>
      {#if data.ownedMissing.length}<p>Build and retain these missing inputs first:</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Package</th><th>Required version</th><th>Target</th></tr></thead><tbody>{#each data.ownedMissing as pkg}<tr><td><a href={`/maintain/catalog?search=${encodeURIComponent(pkg.name)}`}>{pkg.name}</a></td><td>{pkg.version}</td><td>{pkg.architecture}</td></tr>{/each}</tbody></table></div>{#if data.ownedRequired - data.ownedAvailable > data.ownedMissing.length}<p>Showing first 100 missing versions.</p>{/if}
      {:else if data.canManage && data.current && data.ownedRequired}<form method="POST" action="?/assemble" class="review-form" use:enhance>
        {#each data.ownedConflicts as choice}<div class="field"><label for={`provider-${choice.key}`}>{choice.name} {choice.version}: package archives have different checksums</label><select id={`provider-${choice.key}`} name={`provider:${choice.key}`} required><option value="">Choose reviewed package archive</option>{#each choice.candidates as candidate}<option value={candidate.origin}>Attempt {candidate.attempt} · SHA-256 {candidate.sha256.slice(0, 16)}</option>{/each}</select><p>{#each choice.candidates as candidate}<a href={`/maintain/builds/${candidate.buildId}`}>Inspect attempt {candidate.attempt} ({candidate.sha256.slice(0, 8)})</a> {/each}</p></div>{/each}
        <div class="field"><label for="assembly-reason">Reason for owned input set</label><textarea id="assembly-reason" name="reason" required maxlength="2000" placeholder="Replace the captured seed with retained native packages for the final rebuild"></textarea></div><button class="button button--primary" type="submit">Prepare owned lock for review</button>
      </form>{/if}
    </section>
    <section class="workbench-panel"><h2>Packages and keys</h2><form method="GET" class="filter-bar"><div class="field"><label for="package-search">Package name</label><input id="package-search" name="search" value={data.search} maxlength="128" /></div><button class="button" type="submit">Filter</button></form><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Package</th><th>Version / target</th><th>Origin</th><th>Signing key</th></tr></thead><tbody>{#each data.packages as pkg}<tr><td><a href={object(pkg.package.sha256, pkg.filename)} download={pkg.filename}>{pkg.name}</a><div class="hash">{pkg.package.sha256}</div><a href={object(pkg.signature.sha256, pkg.filename + '.sig')}>Detached signature</a></td><td>{pkg.version}<div class="timestamp">{pkg.architecture}</div></td><td><a href={object(pkg.originEvidence)}>{pkg.origin === 'external-bootstrap' ? 'External capture' : 'Signed native build'}</a></td><td><a class="hash" href={object(pkg.publicKey.sha256, pkg.fingerprint + '.asc')}>{pkg.fingerprint}</a></td></tr>{/each}</tbody></table></div><nav class="release-actions" aria-label="Input packages pagination">{#if data.offset > 0}<a class="button" href={page(Math.max(0, data.offset - 100))}>Previous packages</a>{/if}{#if data.hasMore}<a class="button" href={page(data.offset + 100)}>Next packages</a>{/if}</nav></section>
  </section>
</MaintainerShell>
<style>.input-review { padding-block: var(--space-md); border-bottom: 1px solid var(--color-rule); }</style>
