# Private AArch64 runtime for template acceptance. Build context is the
# signature-verified Arch Linux ARM rootfs plus the package archive retained by
# Dockerfile.template-matrix-aarch64. This image never inherits the builder.
FROM scratch
COPY . /

RUN pacman-key --init && pacman-key --populate archlinuxarm \
    && cp /etc/pacman.conf /tmp/opr-pacman.conf \
    && sed -i '/^[#[:space:]]*DownloadUser[[:space:]]*=/d; /^[#[:space:]]*DisableSandboxSyscalls[[:space:]]*$/d; /^\[options\]$/a DownloadUser = root\nDisableSandboxSyscalls\nDisableSandboxFilesystem' /tmp/opr-pacman.conf \
    && pacman --config /tmp/opr-pacman.conf -Syu --noconfirm --needed \
      bash glibc gcc-libs python nodejs xorg-server-xvfb gtk3 nss alsa-lib libxss \
      libx11 libxcb libxcomposite libxdamage libxrandr mesa libdrm at-spi2-core \
      pango cairo dbus libpulse \
    && pacman --config /tmp/opr-pacman.conf -U --noconfirm /opt/electron43-arm-runtime.pkg.tar.zst \
    && pacman --config /tmp/opr-pacman.conf -Scc --noconfirm \
    && rm -f /opt/electron43-arm-runtime.pkg.tar.zst /tmp/opr-pacman.conf \
    && rm -rf /etc/pacman.d/gnupg/openpgp-revocs.d /etc/pacman.d/gnupg/private-keys-v1.d

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
