<script lang="ts">
  import { onMount } from 'svelte';
  import { enhance } from '$app/forms';
  import { invalidateAll } from '$app/navigation';
  import MaintainerShell from '$lib/components/MaintainerShell.svelte';
  import RecipeCaptureUpload from '$lib/components/RecipeCaptureUpload.svelte';
  import { externalPackageSource } from '$lib/distribution';
  import { importDispositionLabels } from '$lib/imports';
  import { startVisibleRefresh } from '$lib/visible-refresh';
  import type { ActionData, PageData } from './$types';

  export let data: PageData;

  export let form: ActionData;

  let busy = false;

  const pending = () => { busy = true;

 return async ({ update }: { update: () => Promise<void> }) => { await update(); busy = false; }; };

  const href = (values: Record<string, string>) => `?${new URLSearchParams(values)}`;

  $: sourceGaps = data.manifest.sources.filter((source) => source.status !== 'captured');

  onMount(() => startVisibleRefresh(() => data.record.status === 'capturing', () => { void invalidateAll(); }));
</script>
<svelte:head><title>{data.manifest.kind} {data.manifest.channel} · import reconciliation · omapkg</title></svelte:head>
<MaintainerShell active="imports" user={data.user}>
  <section class="maintainer-page">
    <header class="maintainer-page__head"><div><a href="/maintain/imports">Repository imports</a><h1>{data.manifest.kind === 'arch' ? 'Arch upstream' : data.manifest.kind === 'opr' ? 'Existing OPR' : 'Omarchy baseline'} · {data.manifest.channel}</h1><p>{data.received} of {data.record.expected_count} captured package records uploaded. Source snapshots stay immutable while ownership and build work progresses.</p>{#each data.observedVersions as item}<p>Observed Omarchy package: <strong>{item.version}</strong> · {item.target}</p>{/each}</div><span class="tag">{data.record.status === 'capturing' ? 'Capture upload in progress' : 'Metadata captured'}</span></header>
    {#if form?.error}<p class="form-notice form-notice--danger" role="alert">{form.error}</p>{:else if form?.success}<p class="notice-bar" role="status">Import review recorded. No package was admitted or published by this action.</p>{/if}
    <section class="workbench-panel"><h2>Import phases</h2><ol class="import-phases"><li><strong>Capture:</strong> {data.record.status === 'capturing' ? 'Uploading and verifying index' : 'Recorded'}{#if sourceGaps.length} · {sourceGaps.length} unavailable sources recorded below{/if}</li><li><strong>Original recipes:</strong> {data.recipeCoverage.retained} / {data.recipeCoverage.total} source recipe mappings retained; {data.recipeCoverage.total - data.recipeCoverage.retained} missing. Split outputs share one recipe per captured repository and target. Of the retained mappings, {data.recipeCoverage.matching} have matching original metadata, {data.recipeCoverage.differing} differ and {data.recipeCoverage.missingMetadata} lack usable original metadata. Native inspection and review remain required.</li><li><strong>Ownership review:</strong> {data.coverage.admitted} / {data.coverage.captured} records have an admitted output identity; {data.counts.unreviewed ?? 0} import records still need a disposition.</li><li><strong>OPR replacements:</strong> {data.counts.replacement ?? 0} records marked for replacement; {data.counts.blocked ?? 0} explicitly blocked. <a href="/maintain/dependencies">Open dependency admission</a></li><li><strong>Native builds:</strong> {data.coverage.built} / {data.coverage.captured} records have matching owned, reviewed build evidence for the captured target/version.</li><li><strong>Baseline reconciliation:</strong> {data.selectedReport ? data.selectedReport.summary.matchesBaseline ? 'Captured metadata matches the selected repository targets' : 'Differences or coverage gaps remain' : 'Choose a baseline below'}.</li><li><strong>Release readiness:</strong> Requires all required sources, ownership, replacements, native/system tests and reviewed release evidence. An inventory comparison does not grant release approval.</li></ol>{#if data.counts.excluded}<p class="form-notice">{data.counts.excluded} exclusions remain visible in the denominator. A recorded reason does not make a required package present.</p>{/if}</section>
    <section class="workbench-panel"><h2>Captured repositories and targets</h2><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Repository / target</th><th>Capture</th><th>Database signature report</th><th>Source evidence</th></tr></thead><tbody>{#each data.manifest.sources as source}<tr><td>{source.collection} / {source.target}</td><td>{source.status === 'captured' ? `${source.entries} package records` : 'Unavailable'}{#if source.error}<p class:form-notice--danger={!(source.target === 'aarch64' && (data.manifest.kind === 'omarchy' || externalPackageSource(source.url)))} class="form-notice">{source.error}{#if source.target === 'aarch64' && data.manifest.kind === 'omarchy'} · No existing ARM baseline; qualify a new owned target.{/if}</p>{/if}</td><td>{source.signature}{#if source.signature !== 'verified'}<div class="timestamp">Captured metadata is not independent trust approval.</div>{/if}</td><td><a href={source.url}>Captured source URL</a>{#if source.sha256}<details><summary>Database digest</summary><p class="hash">{source.sha256}</p></details>{/if}</td></tr>{/each}</tbody></table></div><p>ARM reference metadata from ALARM requires OPR-managed replacements. An absent Omarchy ARM repository is a new target to qualify, not a blocker. Our own ARM package coverage, native builds and system tests remain required.</p></section>
    <section class="workbench-panel" id="baseline-comparison"><h2>Compare with Omarchy stable, RC, edge or existing OPR</h2><p>Choose a separately captured baseline. Comparison includes missing and extra packages, full versions, artifact digests, target architectures and dependency metadata within the matching repository scope.</p>
      {#if data.canManage}<form method="POST" action="?/reconcile" class="filter-bar" use:enhance={pending}><div class="field"><label for="baseline-id">Captured baseline</label><select id="baseline-id" name="baselineId" required><option value="">Choose an immutable capture</option>{#each data.captures as capture}<option value={capture.id}>{capture.manifest.kind} · {capture.manifest.channel} · {capture.expected_count} records · {new Date(capture.created_at * 1000).toISOString().slice(0, 16)}</option>{/each}</select></div><button class="button button--primary" type="submit" disabled={busy || data.record.status === 'capturing'}>{busy ? 'Comparing captured sets…' : 'Compare package sets'}</button></form>{/if}
      {#if !data.captures.length}<p class="notice-bar">Capture an Omarchy stable baseline from the import workspace first. RC and edge use separate captures; existing OPR can be compared with its own captured repository.</p>{/if}
      {#if data.selectedReport}{@const report = data.selectedReport.summary}<h3>Comparison against {report.baselineChannel}</h3><p>Compared repositories: <strong>{report.scope.join(', ')}</strong>.</p>{#if data.uncomparedBaselineSources.length}<div class="notice-bar"><p>Other baseline repositories are outside this comparison. Their packages still need import and reconciliation before full-system readiness.</p><ul>{#each data.uncomparedBaselineSources as source}<li>{source.collection} / {source.target}: {source.entries} captured records are not compared here.</li>{/each}</ul></div>{/if}<p><strong>{report.matchesBaseline ? 'Selected repository metadata matches' : report.coverageComplete ? 'Selected repository coverage complete; differences remain' : 'Coverage incomplete'}</strong> · {report.baselinePackages} baseline records / {report.candidatePackages} candidate records.</p><p>{report.counts.missing} missing · {report.counts.extra} extra · {report.counts.version} version differences · {report.counts.architecture} architecture differences · {report.counts.artifact} artifact differences · {report.counts.metadata} metadata differences.</p>{#if report.sourceGaps.length}<ul class="form-notice form-notice--danger">{#each report.sourceGaps as gap}<li>{gap}</li>{/each}</ul>{/if}{#if report.sourceWarnings.length}<details><summary>Source verification limits ({report.sourceWarnings.length})</summary><ul>{#each report.sourceWarnings as warning}<li>{warning}</li>{/each}</ul></details>{/if}
        {#if report.newTargets?.length}<section class="notice-bar" aria-labelledby="new-arm-target"><div><h3 id="new-arm-target">New ARM target to qualify</h3><p>Omarchy has no captured ARM baseline for these repositories. This does not block import or baseline matching. ARM reference entries are not counted as unexpected extra packages.</p><ul>{#each report.newTargets as target}<li>{target.collection} / {target.target}: {target.referencePackages} reference records captured; owned package coverage and native/system qualification still required.</li>{/each}</ul></div></section>{/if}
        {#if report.qualificationNotes?.length}<details><summary>New-target and reference notes</summary><ul>{#each report.qualificationNotes as note}<li>{note}</li>{/each}</ul></details>{/if}
        {#if report.schemaVersion < 2}<p class="notice-bar">This historical comparison used earlier ARM-baseline rules. Re-run it to classify absent Omarchy ARM repositories as new targets.</p>{/if}
        <form method="GET" class="filter-bar"><input type="hidden" name="report" value={data.selectedReport.id} /><div class="field"><label for="difference-kind">Show differences</label><select id="difference-kind" name="difference" value={data.differenceKind}><option value="">All differences</option>{#each ['missing', 'extra', 'version', 'architecture', 'artifact', 'metadata'] as kind}<option value={kind}>{kind}</option>{/each}</select></div><button class="button" type="submit">Filter comparison</button></form>
        {#if data.differences.length}<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Package / target</th><th>Difference</th><th>Baseline</th><th>This capture</th></tr></thead><tbody>{#each data.differences as item}<tr><td>{item.name}<div class="timestamp">{item.collection} / {item.target}</div></td><td>{item.kind}</td><td>{item.baseline?.version ?? 'Absent'}{#if item.baseline}<details><summary>Artifact digest</summary><p class="hash">{item.baseline.sha256}</p></details>{/if}</td><td>{item.candidate?.version ?? 'Missing'}{#if item.candidate}<details><summary>Artifact digest</summary><p class="hash">{item.candidate.sha256}</p></details>{/if}</td></tr>{/each}</tbody></table></div>{:else}<p>No package differences match this filter. Repository/architecture gaps above still apply.</p>{/if}
        {#if data.differences.length === 50}<a class="button" href={href({ report: data.selectedReport.id, difference: data.differenceKind, differenceAfter: data.differences.at(-1)!.key })}>Next differences</a>{/if}
        <p><a href={`/maintain/imports/${report.baselineId}`}>Open exact baseline evidence</a></p>
      {/if}
      {#if data.comparisons.length > 1}<details><summary>Comparison history</summary><ul>{#each data.comparisons as comparison}<li><a href={href({ report: comparison.id })}>{comparison.summary.baselineChannel} · {comparison.summary.differences} package differences · {comparison.summary.sourceGaps.length} source gaps</a></li>{/each}</ul></details>{/if}
    </section>
    {#if data.canManage && data.record.status !== 'capturing'}<section class="workbench-panel"><details><summary>Preserve original recipe files</summary><p>Attach an exact upstream Git directory to this inventory. Source mapping, missing metadata and OPR admission work remain visible for review.</p><RecipeCaptureUpload importId={data.record.id} sources={data.manifest.sources} /></details></section>{/if}
    <section class="workbench-panel"><h2>Review captured packages</h2><form class="filter-bar" method="GET"><div class="field"><label for="import-search">Package name</label><input id="import-search" type="search" name="q" value={data.search} /></div><div class="field"><label for="import-disposition">Review state</label><select id="import-disposition" name="disposition" value={data.disposition}><option value="">All records</option>{#each Object.entries(importDispositionLabels) as [key, label]}<option value={key}>{label}</option>{/each}</select></div><button class="button" type="submit">Find packages</button></form>
      <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Package</th><th>Captured version / target</th><th>Review state</th><th>Action</th></tr></thead><tbody>{#each data.entries as entry}<tr><td>{entry.name}<div class="timestamp">{entry.collection} · build identity {entry.pkgbase}</div></td><td>{entry.metadata.version}<div class="timestamp">{entry.target_architecture} · content {entry.architecture}</div></td><td>{importDispositionLabels[entry.disposition]}{#if entry.reason}<p>{entry.reason}</p>{/if}</td><td><a href={`/maintain/catalog?${new URLSearchParams({ q: entry.pkgbase })}`}>Find owned policy</a>{#if entry.recipeCapture}<p><a href={`/maintain/recipes/${entry.recipeCapture.capture_sha256}`}>{entry.recipeCapture.inspected ? 'Original recipe · inspected' : entry.recipeCapture.matches ? 'Original recipe · metadata matches' : entry.recipeCapture.metadata_present ? 'Original recipe · mapping differs' : 'Original recipe · inspection required'}</a></p>{:else}<p class="timestamp">Original recipe not captured</p>{/if}<details><summary>Captured package evidence</summary><pre class="code-block">{JSON.stringify(entry.metadata, null, 2)}</pre></details>{#if data.canManage}<details><summary>Record import disposition</summary><form method="POST" action="?/review" class="review-form" use:enhance={pending}><input type="hidden" name="sourceId" value={entry.source_id} /><input type="hidden" name="name" value={entry.name} /><label for={`disposition-${entry.source_id}-${entry.name}`}>Disposition</label><select id={`disposition-${entry.source_id}-${entry.name}`} name="disposition"><option value="linked">Link admitted owned identity</option><option value="replacement">OPR replacement needed</option><option value="blocked">Blocked</option><option value="excluded">Explicit exclusion (still visible)</option></select><label for={`reason-${entry.source_id}-${entry.name}`}>Reason</label><textarea id={`reason-${entry.source_id}-${entry.name}`} name="reason" required maxlength="2000" rows="2"></textarea><button class="button" type="submit" disabled={busy}>Record disposition</button></form></details>{/if}</td></tr>{/each}</tbody></table></div>
      {#if !data.entries.length}<p>No package records match these filters.</p>{/if}{#if data.entries.length === 50}<a class="button" href={href({ q: data.search, disposition: data.disposition, after: `${data.entries.at(-1)!.source_id}/${data.entries.at(-1)!.name}` })}>Next package records</a>{/if}
    </section>
  </section>
</MaintainerShell>
<style>.import-phases { display: grid; gap: var(--space-md); padding-inline-start: var(--space-xl); } td details { margin-block: var(--space-sm); } td form { min-width: 12rem; } td textarea, td select { max-width: 100%; }</style>
